name: chat_messenger
description: Woonkly
publish_to: "none"     # No se publicará en pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.24.0 <4.0.0"

#######################################################################
# DEPENDENCIAS
#######################################################################
dependencies:
  # ──────────────────── SDK ────────────────────
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter               # ← obliga a usar intl 0.20.2
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2

  # ──────────────────── Firebase ────────────────────
  firebase_core:        ^3.13.1
  cloud_firestore:      ^5.6.8
  firebase_auth:        ^5.5.4
  firebase_storage:     ^12.4.6
  firebase_messaging:   ^15.2.6
  firebase_database:    ^11.3.6
  cloud_functions:      ^5.5.1

  # ──────────────────── Wallet Connection ────────────────────
  walletconnect_dart: ^0.0.11
  walletconnect_flutter_v2: ^2.0.2
  web3dart: ^2.7.3
  url_launcher: ^6.3.1
  convert: ^3.1.1

  # ──────────────────── Ads ────────────────────
  google_mobile_ads:    ^6.0.0

  # ──────────────────── Estado / UI / Utils ────────────────────
  get:                  ^4.7.2
  flutter_iconly:       1.0.2
  google_fonts:         ^6.2.1
  flutter_svg:          ^2.1.0
  cached_network_image: ^3.3.1

  # ──────────────────── Multimedia ────────────────────
  camera:               ^0.11.1
  image_picker:         ^0.8.9
  image_cropper:        ^9.1.0
  video_player:         ^2.9.5
  video_editor:         ^3.0.0
  chewie:               ^1.11.3
  giphy_get:            ^3.6.1            # trae intl 0.20.2 vía localizations
  assets_audio_player:  ^3.1.1
  audioplayers:         ^6.4.0

  # ──────────────────── Ficheros / Storage ────────────────────
  path_provider:        ^2.1.5
  path:                 ^1.9.1
  mime:                 ^2.0.0
  file_picker:          ^10.1.9
  wechat_assets_picker: ^9.5.1
  share_plus:           ^11.0.0

  # ──────────────────── Permisos / Geolocalización ────────────────────
  permission_handler:   ^12.0.0+1
  geolocator:           ^12.0.0
  record:               ^6.0.0

  # ──────────────────── Networking ────────────────────
  http:                 ^1.2.1

  # ──────────────────── Cifrado ────────────────────
  encrypt:              ^5.0.3
  crypto:               ^3.0.6

  # ──────────────────── Video-llamadas ────────────────────
  agora_rtc_engine:     ^6.5.2
  flutter_ringtone_player: ^4.0.0+4

  # ──────────────────── Otros ────────────────────
  flutter_spinkit:      ^5.2.1
  timeago:              ^3.7.1
  shimmer:              ^3.0.0
  emoji_picker_flutter: ^4.3.0
  uuid:                 ^4.0.0
  marquee:              ^2.3.0
  fraction:             ^5.0.5
  story_view:           ^0.16.5
  async:                ^2.13.0
  rxdart:               ^0.27.7
  easy_rich_text:       ^2.2.0
  device_info_plus:     ^11.4.0
  fl_chart:             ^0.66.2

#######################################################################
# OVERRIDES (fijamos intl 0.20.2 para TODOS)
#######################################################################
dependency_overrides:
  intl: 0.20.2                 # ← versión única en todo el proyecto
  fading_edge_scrollview: ^4.1.1
  uuid: ^4.0.0                 # ← forzamos versión 4.x para web3dart

#######################################################################
# DEV DEPENDENCIAS
#######################################################################
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.3.0

#######################################################################
# ASSETS / ICONOS / SPLASH
#######################################################################
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/sounds/
    - assets/flags/
    - assets/icons/extensions/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/launcher_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: "assets/images/app_logo.png"
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    color_dark: "#000000"
    image: "assets/images/app_logo.png"